server:
  port: 8086

spring:
  application:
    name: equipment-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:trabix_db}
    username: ${DB_USER:trabix_admin}
    password: ${DB_PASSWORD:trabix_secure_2024}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Configuración JWT
jwt:
  secret: ${JWT_SECRET:clave_secreta_muy_larga_para_desarrollo_local_trabix_2024_minimo_256_bits}

# Configuración de equipos
trabix:
  equipos:
    mensualidad-default: 10000
    costo-reposicion:
      nevera: 350000
      pijama: 80000

# Logging
logging:
  level:
    com.trabix: DEBUG
